# Generated by Django 4.2 on 2023-05-04 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=256, verbose_name='годы')),
                ('title', models.CharField(max_length=556, verbose_name='заголовок')),
                ('title_ru', models.CharField(max_length=556, null=True, verbose_name='заголовок')),
                ('title_ky', models.CharField(max_length=556, null=True, verbose_name='заголовок')),
                ('description', models.TextField(verbose_name='описание')),
                ('description_ru', models.TextField(null=True, verbose_name='описание')),
                ('description_ky', models.TextField(null=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='history_images', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
        migrations.CreateModel(
            name='MileStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements', models.CharField(max_length=556, verbose_name='достижения')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_milestone', to='history.history')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
            },
        ),
    ]
