# Generated by Django 4.2 on 2023-05-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_history_years'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MileStone',
        ),
    ]
