# Generated by Django 4.2 on 2023-04-24 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('construction_object', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Новости компании', 'Новости компании'), ('Пресс-центр', 'Пресс-центр'), ('Ход строительства', 'Ход строительства')], max_length=20, null=True, verbose_name='категория')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='название')),
                ('title_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='название')),
                ('title_ky', models.CharField(blank=True, max_length=256, null=True, verbose_name='название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='контент')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name='контент')),
                ('content_ky', models.TextField(blank=True, null=True, verbose_name='контент')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images', verbose_name='картинка поста')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='дата создания поста')),
                ('construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_construction', to='construction_object.construction', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images', verbose_name='картинка поста')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_image', to='news_blog.post', verbose_name='пост')),
            ],
        ),
    ]
