# Generated by Django 4.2 on 2023-05-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Новости компании', 'Новости компании'), ('Пресс-центр', 'Пресс-центр'), ('Ход строительства', 'Ход строительства'), ('Вакансии', 'Вакансии')], max_length=20, null=True, verbose_name='категория'),
        ),
    ]
