# Generated by Django 4.2 on 2023-04-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=256, null=True, verbose_name='должность')),
                ('position_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='должность')),
                ('position_ky', models.CharField(blank=True, max_length=256, null=True, verbose_name='должность')),
                ('job_category', models.CharField(blank=True, choices=[('совет директоров', 'совет директоров'), ('генеральный директор', 'генеральный директор'), ('менеджмент', 'менеджмент')], max_length=256, null=True, verbose_name='категория')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='био')),
                ('bio_ru', models.TextField(blank=True, null=True, verbose_name='био')),
                ('bio_ky', models.TextField(blank=True, null=True, verbose_name='био')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
