# Generated by Django 4.2 on 2023-04-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='quote',
            field=models.TextField(default='', verbose_name='цитата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='quote_ky',
            field=models.TextField(null=True, verbose_name='цитата'),
        ),
        migrations.AddField(
            model_name='member',
            name='quote_ru',
            field=models.TextField(null=True, verbose_name='цитата'),
        ),
        migrations.AddField(
            model_name='member',
            name='title',
            field=models.TextField(default='', verbose_name='заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='title_ky',
            field=models.TextField(null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='member',
            name='title_ru',
            field=models.TextField(null=True, verbose_name='заголовок'),
        ),
    ]
