# Generated by Django 4.2 on 2023-04-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0002_member_quote_member_quote_ky_member_quote_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='job_category',
            field=models.CharField(blank=True, choices=[('совет директоров', 'совет директоров'), ('генеральный директор', 'генеральный директор'), ('менеджмент', 'менеджмент'), ('инвесторы', 'инвесторы')], max_length=256, null=True, verbose_name='категория'),
        ),
    ]
