# Generated by Django 4.2 on 2023-05-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0003_alter_member_job_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='ФИО')),
                ('company', models.CharField(blank=True, max_length=256, null=True, verbose_name='компания')),
                ('title', models.TextField(verbose_name='описание')),
                ('quote', models.TextField(verbose_name='цитата')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='био')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='job_category',
            field=models.CharField(blank=True, choices=[('совет директоров', 'совет директоров'), ('правление', 'правление'), ('менеджмент', 'менеджмент'), ('инвесторы', 'инвесторы'), ('партнеры', 'партнеры')], max_length=256, null=True, verbose_name='категория'),
        ),
    ]
