# Generated by Django 4.2 on 2023-05-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0004_partner_alter_member_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='company',
            field=models.CharField(default=1, max_length=256, verbose_name='компания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='quote',
            field=models.TextField(blank=True, null=True, verbose_name='цитата'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
