# Generated by Django 4.2 on 2023-05-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0005_alter_partner_company_alter_partner_quote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='name',
        ),
    ]
