# Generated by Django 4.2 on 2023-05-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0006_remove_partner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='биография'),
        ),
        migrations.AlterField(
            model_name='member',
            name='bio_ky',
            field=models.TextField(blank=True, null=True, verbose_name='биография'),
        ),
        migrations.AlterField(
            model_name='member',
            name='bio_ru',
            field=models.TextField(blank=True, null=True, verbose_name='биография'),
        ),
    ]
