# Generated by Django 4.2 on 2023-05-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0007_alter_member_bio_alter_member_bio_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='bio_ky',
            field=models.TextField(blank=True, null=True, verbose_name='био'),
        ),
        migrations.AddField(
            model_name='partner',
            name='bio_ru',
            field=models.TextField(blank=True, null=True, verbose_name='био'),
        ),
        migrations.AddField(
            model_name='partner',
            name='quote_ky',
            field=models.TextField(blank=True, null=True, verbose_name='цитата'),
        ),
        migrations.AddField(
            model_name='partner',
            name='quote_ru',
            field=models.TextField(blank=True, null=True, verbose_name='цитата'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_ky',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_ru',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
