# Generated by Django 4.2 on 2023-05-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='link_video',
            field=models.CharField(default='', max_length=1000, verbose_name='ссылка на видео'),
            preserve_default=False,
        ),
    ]
