# Generated by Django 4.2 on 2023-05-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_configuration_link_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='link_video',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ссылка на видео'),
        ),
    ]
