# Generated by Django 4.2 on 2023-04-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название документа')),
                ('document', models.FileField(upload_to='', verbose_name='документ')),
            ],
        ),
    ]
