# Generated by Django 4.2 on 2023-05-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_document_options_alter_document_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.CharField(max_length=1000, verbose_name='ссылка на документ'),
        ),
    ]
