# Generated by Django 4.2 on 2023-05-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_document_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('история', 'история'), ('корпоративное управление', 'корпоративное управление'), ('инвесторам', 'инвесторам'), ('партнерам', 'партнерам'), ('стандарт ISO 9001', 'стандарт ISO 9001')], default='партнерам', max_length=256, verbose_name='категория'),
            preserve_default=False,
        ),
    ]
