# Generated by Django 4.2 on 2023-04-22 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('жилой', 'Жилой'), ('коммерческий', 'Коммерческий')], max_length=256, null=True, verbose_name='тип объекта')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='название')),
                ('main_picture', models.ImageField(upload_to='construction_images', verbose_name='Главная фотография')),
                ('street_address', models.CharField(max_length=200, verbose_name='адрес улицы')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='долгота')),
                ('offer', models.CharField(blank=True, choices=[('Старт продаж', 'Старт продаж'), ('Скидки до 10%', 'Скидки до 10%'), ('Последнее предложение', 'Последнее предложение'), ('Продажи завершины', 'Продажи завершины')], max_length=256, null=True, verbose_name='предложение')),
                ('cost_per_square_meter', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость за 1 m2')),
                ('construction_state', models.CharField(blank=True, choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], default='10%', max_length=256, null=True, verbose_name='готовность объекта')),
                ('construction_completion_quarter', models.CharField(blank=True, choices=[('I', 'Сдача в I квартале'), ('II', 'Сдача в II квартале'), ('III', 'Сдача в III квартале'), ('IV', 'Сдача в IV квартале')], default='1 квартал', max_length=256, null=True, verbose_name='квартал сдачи объекта')),
                ('min_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальная цена от')),
                ('installment', models.CharField(blank=True, max_length=256, null=True, verbose_name='в рассрочку')),
                ('installment_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='в рассрочку')),
                ('installment_ky', models.CharField(blank=True, max_length=256, null=True, verbose_name='в рассрочку')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание объекта')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='описание объекта')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='описание объекта')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='ссылка на видео')),
                ('is_selling', models.BooleanField(default=False, verbose_name='в продаже')),
                ('is_completed', models.BooleanField(default=False, verbose_name='построен')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=256, unique=True, verbose_name='год')),
            ],
            options={
                'verbose_name': 'Год сдачи объекта',
                'verbose_name_plural': 'Года сдачи объектов',
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('жилой', 'Жилой'), ('коммерческий', 'Коммерческий')], max_length=256, null=True, verbose_name='тип помещения')),
                ('type_ru', models.CharField(blank=True, choices=[('жилой', 'Жилой'), ('коммерческий', 'Коммерческий')], max_length=256, null=True, verbose_name='тип помещения')),
                ('type_ky', models.CharField(blank=True, choices=[('жилой', 'Жилой'), ('коммерческий', 'Коммерческий')], max_length=256, null=True, verbose_name='тип помещения')),
                ('layout_photo', models.ImageField(blank=True, null=True, upload_to='layouts', verbose_name='планировка ')),
                ('design_photo', models.ImageField(blank=True, null=True, upload_to='layouts/', verbose_name='3D модель')),
                ('rooms', models.CharField(blank=True, choices=[('Studio', 'Студия'), ('1', '1 комната'), ('2', '2 комнаты'), ('3', '3 комнаты'), ('4', '4 комнаты'), ('5', '5 комнат')], max_length=6, null=True, verbose_name='количество комнат')),
                ('rooms_ru', models.CharField(blank=True, choices=[('Studio', 'Студия'), ('1', '1 комната'), ('2', '2 комнаты'), ('3', '3 комнаты'), ('4', '4 комнаты'), ('5', '5 комнат')], max_length=6, null=True, verbose_name='количество комнат')),
                ('rooms_ky', models.CharField(blank=True, choices=[('Studio', 'Студия'), ('1', '1 комната'), ('2', '2 комнаты'), ('3', '3 комнаты'), ('4', '4 комнаты'), ('5', '5 комнат')], max_length=6, null=True, verbose_name='количество комнат')),
                ('square_meters', models.PositiveIntegerField(blank=True, null=True, verbose_name='площадь помещения')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='этаж')),
                ('building', models.CharField(blank=True, max_length=256, null=True, verbose_name='корпус')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='цена')),
                ('mortgage', models.CharField(blank=True, max_length=256, null=True, verbose_name='в ипотеку')),
                ('mortgage_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='в ипотеку')),
                ('mortgage_ky', models.CharField(blank=True, max_length=256, null=True, verbose_name='в ипотеку')),
                ('construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layout', to='construction_object.construction', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='название особенности')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='название особенности')),
                ('title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='название особенности')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание особенности')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='описание особенности')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='описание особенности')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='features', verbose_name='фотография')),
                ('construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='construction_object.construction', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'Особенность',
                'verbose_name_plural': 'Особенности',
            },
        ),
        migrations.CreateModel(
            name='ConstructionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='construction_images', verbose_name='Фотографии')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_image', to='construction_object.construction')),
            ],
            options={
                'verbose_name': 'Фотография объекта',
                'verbose_name_plural': 'Фотографии объекта',
            },
        ),
        migrations.AddField(
            model_name='construction',
            name='construction_completion_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='construction_completion_year', to='construction_object.year', verbose_name='год сдачи объекта'),
        ),
        migrations.AddField(
            model_name='construction',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='construction_district', to='construction_object.district', verbose_name='район'),
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='краткое описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='краткое описание')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='краткое описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='advantage_logo', verbose_name='лого')),
                ('construction', models.ManyToManyField(related_name='advantage_of_construction', to='construction_object.construction')),
            ],
            options={
                'verbose_name': 'Плюс объекта',
                'verbose_name_plural': 'Плюсы объекта',
            },
        ),
    ]
