# Generated by Django 4.2 on 2023-04-12 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construction',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='construction',
            name='title_ru',
        ),
    ]
