# Generated by Django 4.2 on 2023-04-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='rooms_ky',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='rooms_ru',
        ),
        migrations.AlterField(
            model_name='advantage',
            name='construction',
            field=models.ManyToManyField(related_name='advantage_of_construction', to='construction_object.construction', verbose_name='Объект'),
        ),
    ]
