# Generated by Django 4.2 on 2023-04-28 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.PositiveIntegerField(blank=True, null=True, verbose_name='Культура и отдых')),
                ('medicine', models.PositiveIntegerField(blank=True, null=True, verbose_name='Медицина')),
                ('education', models.PositiveIntegerField(blank=True, null=True, verbose_name='Образование')),
                ('finance', models.PositiveIntegerField(blank=True, null=True, verbose_name='Финансы')),
                ('trade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Торговля')),
                ('food', models.PositiveIntegerField(blank=True, null=True, verbose_name='Еда')),
                ('sport', models.PositiveIntegerField(blank=True, null=True, verbose_name='Спорт')),
                ('service', models.PositiveIntegerField(blank=True, null=True, verbose_name='Услуги')),
                ('construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infrasrtucture_nearby', to='construction_object.construction', verbose_name='объект')),
            ],
        ),
    ]
