# Generated by Django 4.2 on 2023-04-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0002_remove_construction_title_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='offer',
            field=models.CharField(blank=True, choices=[('Старт продаж', 'Старт продаж'), ('Скидки до 10%', 'Скидки до 10%'), ('Последнее предложение', 'Последнее предложение'), ('Продажи завершины', 'Продажи завершины')], max_length=256, null=True, verbose_name='предложение'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='offer_ky',
            field=models.CharField(blank=True, choices=[('Старт продаж', 'Старт продаж'), ('Скидки до 10%', 'Скидки до 10%'), ('Последнее предложение', 'Последнее предложение'), ('Продажи завершины', 'Продажи завершины')], max_length=256, null=True, verbose_name='предложение'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='offer_ru',
            field=models.CharField(blank=True, choices=[('Старт продаж', 'Старт продаж'), ('Скидки до 10%', 'Скидки до 10%'), ('Последнее предложение', 'Последнее предложение'), ('Продажи завершины', 'Продажи завершины')], max_length=256, null=True, verbose_name='предложение'),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
