# Generated by Django 4.2 on 2023-04-29 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0002_infrastructure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat',
            options={'verbose_name': 'Планировка', 'verbose_name_plural': 'Планировки'},
        ),
        migrations.RemoveField(
            model_name='flat',
            name='building',
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=256, verbose_name='Название Блока')),
                ('plan_model', models.FileField(blank=True, null=True, upload_to='', verbose_name='Планировка')),
                ('sides', models.CharField(blank=True, choices=[('Север', 'Север'), ('Юг', 'Юг'), ('Восток', 'Восток'), ('Запад', 'Запад')], max_length=20, null=True, verbose_name='Сторона')),
                ('construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_objects', to='construction_object.construction', verbose_name='объект')),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_flat', to='construction_object.block', verbose_name='корпус'),
        ),
    ]
