# Generated by Django 4.2 on 2023-04-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0002_remove_flat_rooms_ky_remove_flat_rooms_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='type_ky',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='type_ru',
        ),
        migrations.AddField(
            model_name='construction',
            name='key_words',
            field=models.CharField(blank=True, max_length=556, null=True, verbose_name='Ключевые слова'),
        ),
    ]
