# Generated by Django 4.2 on 2023-04-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0003_alter_flat_options_remove_flat_building_block_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterModelOptions(
            name='infrastructure',
            options={'verbose_name': 'Инфраструктура', 'verbose_name_plural': 'Инфраструктуры'},
        ),
        migrations.AddField(
            model_name='block',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Продан'),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='block',
            name='plan_model',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='План'),
        ),
    ]
