# Generated by Django 4.2 on 2023-04-12 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0003_alter_construction_offer_alter_construction_offer_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construction',
            name='offer_ky',
        ),
        migrations.RemoveField(
            model_name='construction',
            name='offer_ru',
        ),
    ]
