# Generated by Django 4.2 on 2023-05-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0004_alter_block_options_alter_infrastructure_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construction',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='construction',
            name='is_selling',
        ),
        migrations.AddField(
            model_name='construction',
            name='selling_status',
            field=models.CharField(blank=True, choices=[('selling', 'selling'), ('built', 'built')], max_length=25, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='key_words',
            field=models.CharField(blank=True, max_length=556, null=True, verbose_name='Ключевые слова (SEO)'),
        ),
    ]
