# Generated by Django 4.2 on 2023-04-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0004_remove_construction_offer_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='type',
            field=models.CharField(blank=True, choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], max_length=256, null=True, verbose_name='тип объекта'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='type',
            field=models.CharField(blank=True, choices=[('жилой', 'Жилой'), ('коммерческий', 'Коммерческий')], max_length=256, null=True, verbose_name='тип помещения'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='type_ky',
            field=models.CharField(blank=True, choices=[('жилой', 'Жилой'), ('коммерческий', 'Коммерческий')], max_length=256, null=True, verbose_name='тип помещения'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='type_ru',
            field=models.CharField(blank=True, choices=[('жилой', 'Жилой'), ('коммерческий', 'Коммерческий')], max_length=256, null=True, verbose_name='тип помещения'),
        ),
    ]
