# Generated by Django 4.2 on 2023-05-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0005_remove_construction_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='построен'),
        ),
        migrations.AddField(
            model_name='construction',
            name='is_selling',
            field=models.BooleanField(default=False, verbose_name='в продаже'),
        ),
    ]
