# Generated by Django 4.2 on 2023-04-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0005_construction_type_alter_flat_type_alter_flat_type_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='type',
            field=models.CharField(blank=True, choices=[('жилой', 'Жилой'), ('коммерческий', 'Коммерческий')], max_length=256, null=True, verbose_name='тип объекта'),
        ),
    ]
