# Generated by Django 4.2 on 2023-05-04 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0010_alter_construction_selling_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='фото квартиры')),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flat_images', to='construction_object.flat')),
            ],
        ),
    ]
