# Generated by Django 4.2 on 2023-05-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0011_flatimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flatimages',
            options={'verbose_name': 'Фото Объекта', 'verbose_name_plural': 'Фото Объектов'},
        ),
    ]
