# Generated by Django 4.2 on 2023-05-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0012_alter_flatimages_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construction',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='construction',
            name='is_selling',
        ),
    ]
