# Generated by Django 4.2 on 2023-05-06 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0013_remove_construction_is_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('date', models.DateField(blank=True, null=True, verbose_name='дата')),
                ('is_active', models.BooleanField(default=False, verbose_name='актуальный')),
                ('construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='construction_object.construction', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'Прайс Лист',
                'verbose_name_plural': 'Прайс Лист',
            },
        ),
    ]
