# Generated by Django 4.2 on 2023-05-11 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0014_pricelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='design_photo',
        ),
        migrations.AlterField(
            model_name='advantage',
            name='construction',
            field=models.ManyToManyField(related_name='advantage_of_construction', to='construction_object.construction', verbose_name='объект'),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_name',
            field=models.CharField(max_length=256, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='block',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='продан'),
        ),
        migrations.AlterField(
            model_name='block',
            name='plan_model',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='план'),
        ),
        migrations.AlterField(
            model_name='block',
            name='sides',
            field=models.CharField(blank=True, choices=[('Север', 'Север'), ('Юг', 'Юг'), ('Восток', 'Восток'), ('Запад', 'Запад')], max_length=20, null=True, verbose_name='сторона'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='cost_per_square_meter',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='стоимость за 1 m2'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='key_words',
            field=models.CharField(blank=True, max_length=556, null=True, verbose_name='ключевые слова (SEO)'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='main_picture',
            field=models.ImageField(upload_to='construction_images', verbose_name='главная фотография'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='min_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='минимальная цена от'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='offer',
            field=models.CharField(blank=True, choices=[('новый', 'новый'), ('в процессе', 'в процессе'), ('в завершении', 'в завершении')], max_length=256, null=True, verbose_name='предложение'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='selling_status',
            field=models.CharField(choices=[('selling', 'в продаже'), ('built', 'построено')], default='в продаже', max_length=25, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='constructionimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='construction_images', verbose_name='фотографии'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='холл')),
                ('dining_room', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='гостинная')),
                ('kitchen', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='кухня')),
                ('balcony_1', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='балкон 1')),
                ('balcony_2', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='балкон 2')),
                ('balcony_3', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='балкон 3')),
                ('bath', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='ванная')),
                ('wc_1', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='санузел 1')),
                ('wc_2', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='санузел 1')),
                ('bed_room_1', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='спальня 1')),
                ('bed_room_2', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='спальня 2')),
                ('bed_room_3', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='спальня 3')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='construction_object.flat')),
            ],
            options={
                'verbose_name': 'комната',
                'verbose_name_plural': 'комнаты',
            },
        ),
    ]
