# Generated by Django 4.2 on 2023-05-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0015_remove_flat_design_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='balcony_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='балкон 1'),
        ),
        migrations.AlterField(
            model_name='room',
            name='balcony_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='балкон 2'),
        ),
        migrations.AlterField(
            model_name='room',
            name='balcony_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='балкон 3'),
        ),
        migrations.AlterField(
            model_name='room',
            name='bath',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ванная'),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_room_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='спальня 1'),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_room_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='спальня 2'),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_room_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='спальня 3'),
        ),
        migrations.AlterField(
            model_name='room',
            name='dining_room',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='гостинная'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hall',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='холл'),
        ),
        migrations.AlterField(
            model_name='room',
            name='kitchen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='кухня'),
        ),
        migrations.AlterField(
            model_name='room',
            name='wc_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='санузел 1'),
        ),
        migrations.AlterField(
            model_name='room',
            name='wc_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='санузел 1'),
        ),
    ]
