# Generated by Django 4.2 on 2023-05-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0016_alter_room_balcony_1_alter_room_balcony_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='balcony_3',
        ),
        migrations.AddField(
            model_name='room',
            name='terrasse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='терраса'),
        ),
        migrations.AlterField(
            model_name='room',
            name='wc_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='санузел 2'),
        ),
    ]
