# Generated by Django 4.2 on 2023-05-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0017_remove_room_balcony_3_room_terrasse_alter_room_wc_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='sub_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='этаж'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='square_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='площадь помещения'),
        ),
    ]
