# Generated by Django 4.2 on 2023-05-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0018_construction_sub_title_alter_flat_floor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructionimage',
            options={'verbose_name': 'Фотография для карусели', 'verbose_name_plural': 'Фотографии для карусели'},
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена в долларах $'),
        ),
    ]
