# Generated by Django 4.2 on 2023-05-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_object', '0019_alter_constructionimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'квадратура', 'verbose_name_plural': 'квадратура'},
        ),
        migrations.RemoveField(
            model_name='block',
            name='sides',
        ),
        migrations.AlterField(
            model_name='construction',
            name='sub_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='flatimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='фото планировок'),
        ),
    ]
